
# Site Settings
title: Venkata Guravareddy Resume
url: 'https://bsrgsit.github.io'
baseurl: '/' 

theme_skin: green # blue turquoise green berry orange ceramic

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# publish
